name: Publish to JSR

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.3)'
        required: true
        type: string

jobs:
  publish-jsr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for JSR OIDC authentication
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.18'
      
      - name: Install dependencies
        run: bun install
      
      - name: Update version from tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Updating version to $VERSION"
          sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$VERSION\"/" jsr.json
          sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$VERSION\"/" package.json
      
      - name: Update version from input
        if: github.event.inputs.version
        run: |
          VERSION="${{ github.event.inputs.version }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Updating version to $VERSION"
          sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$VERSION\"/" jsr.json
          sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$VERSION\"/" package.json
      
      - name: Run tests
        run: bun test
      
      - name: Dry run JSR publish
        run: npx jsr publish --dry-run
      
      - name: Publish to JSR
        run: npx jsr publish
      
      - name: Summary
        run: |
          echo "## 🚀 JSR Package Published Successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Package Information:" >> $GITHUB_STEP_SUMMARY
          echo "- **Name**: @tyr/mcp-clipboard" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: $VERSION" >> $GITHUB_STEP_SUMMARY
          echo "- **JSR URL**: https://jsr.io/@tyr/mcp-clipboard" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Installation:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "bunx @tyr/mcp-clipboard" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY